mybirthday=print ("ENTER KAIRA BIRTHDAY")
myfriendbirthday1=print ("ENTER MY FRIEND BIRTHDAY1")
myfriendbirthday2=print("ENTER MY FRIEND BIRTHDAY2" )
myfriendbirthday3=print("ENTER MY FRIEND BIRTHDAY3")
myfriendbirthday4=print("ENTER MY FRIEND BIRTHDAY4")
input("mybirthday")
input("myfriendbirthday1")
input("myfriendbirthday2")
input("myfriendbirthday3")
input("myfriendbirthday4")